site_name: nf-test

theme:
  name: material
  features:
    - navigation.instant
    - tabs
  palette:
    primary: teal
    accent: teal
  icon:
    logo: material/sticker-check-outline
  favicon: images/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - extra.css
repo_url: https://github.com/askimed/nf-test

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Writing Tests:
    - Process Testing: testcases/nextflow_process.md
    - Workflow Testing: testcases/nextflow_workflow.md
    - Pipeline Testing: testcases/nextflow_pipeline.md
  - Writing Assertions:
    - Power Assertions: assertions/assertions.md
    - Files: assertions/files.md
    - Regular Expressions: assertions/regular-expressions.md
    - Using Third-Party Libraries: assertions/libraries.md
  - Command line interface (CLI):
    - init: cli/init.md
    - generate: cli/generate.md
    - test: cli/test.md
  - Configuration: configuration.md
  - nf-test Pipelines: nftest_pipelines.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
