site_name: nf-test

theme:
  name: material
  features:
    - navigation.instant
    - tabs
  palette:
    primary: teal
    accent: teal
  icon:
    logo: material/sticker-check-outline
  favicon: images/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - extra.css
repo_url: https://github.com/lukfor/nf-test/

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Assertions: assertions.md
  - Configuration: configuration.md


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
